version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: benefit-db
    restart: always
    environment:
      POSTGRES_DB: benefit-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - api
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  api:
    driver: bridge